### ISSUE TITLE
Multiple small enhancements

### ISSUE THREAD

**Issue by sjahreis** [linked-planet/ktorbase#7]
As we updated one of our ktorbase-based projects, we identified some small enhancements:
- add `AppBaseUrl` again (see https://github.com/linked-planet/ktorbase/commit/bae404e582ce76b83df53e814e0458080eeac0d1)
- switch from logback to log4j (see `build.gradle`)
- add fontawesome to the frontend dependencies (see `build.gradle`)
- Bitbucket pipeline (see https://github.com/linked-planet/ktorbase/blob/master/bitbucket-pipelines.yml)
  - add environment `uat`
  - change notation of `test`, `uat` and `prod` to lower case
  - add submodule initialization (shouldn't matter if no submodule is present)
  - switch to linktimelabs/docker-build-kotlin-fullstack:latest image for build-step
  - create a CI pipeline
- Upgrade Gradle Wrapper to 7.1
- escape the image version parameter in `deploy.sh` (should be `--parameter-overrides "[$PARAMETER_OVERRIDES\"ServiceImageVersion=$SERVICE_IMAGE_VERSION\"]"`)

**Comment by sjahreis** [comment]
Done!
@weickmanna: Please review

**Comment by weickmanna** [comment]
@sjahreis All good. Tested it with 2 actual projects.
